version: '3'

services:
  api:
    image: poseidon-api:0.1
    environment:
      - "IssuerSigningKey:SigningKey=0439C4537C914A86BAD8A1E8335CE41C"
      - "ConnectionStrings:DefaultConnection=Server=tcp:db,1433;Initial Catalog=Poseidon;Integrated Security=False;Connect Timeout=300;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;User ID=SA;Password=YourStrong!Passw0rd"
    ports:
      - "5000:80"
    networks:
      - poseidon-net
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    networks:
      - poseidon-net

networks:
  poseidon-net:

volumes:
  db-data: