version: '3'

services:
  api:
    build: ./Poseidon
    image: poseidon-api:0.1
    environment:
      - "IssuerSigningKey:SigningKey=0439C4537C914A86BAD8A1E8335CE41C"
      - "ConnectionStrings:DefaultConnection=Server=tcp:database,1433;Initial Catalog=Poseidon;Integrated Security=False;Connect Timeout=300;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;User ID=SA;Password=YourStrong!Passw0rd"
    ports:
      - "5000:80"
    networks:
      - poseidon-net
    depends_on:
      - database

  device-endpoint:
    build: ./PoseidonFA
    image: poseidon-function:0.1
    environment:
      - "BatteryLevelAlarm=20"
      - "ConnectionStrings:DefaultConnection=Server=tcp:database,1433;Initial Catalog=Poseidon;Integrated Security=False;Connect Timeout=300;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;User ID=SA;Password=YourStrong!Passw0rd"
    ports:
      - "8081:80"
    networks: 
      - poseidon-net
    depends_on:
      - database

  database:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    networks:
      - poseidon-net
    volumes:
      - "db-data:/var/opt/mssql"

networks:
  poseidon-net:

volumes:
  db-data: